### PR TITLE
Fixes for issues #126,  #149 and #151 related to eos and nxos bootstrap

### PR DESCRIPTION
**Pull request by acarpi**
Hi, 

Please approve this PR. It contains the fixes for the following issues:

eos-bootstrap:
1. there is an issue when Arista box is booting and the command 'copy running-config startup-config' fails consistently, for two main reasons: ZTP process is still active, eAPI is still down. In my proposed fix I use a simple retry logic for it, up to 5min (yes, it is THAT slow)

nxos-bootstrap:
1. the current logic relies on event-manager to recognize System ready from a given pattern in the syslog, while the bootstrap script relies on a file creation from this applet. This logic fails most of the time (at least on my testing using a Cisco 9332PQ), maybe because event manager starts too late. 
My fix proposes to simply grep the pattern from the syslog, which also removes the need for the customer to have the event manager section in boot config (btw, looks like we were not cleaning that up after the bootstrap script execution? Another reason to get rid of it).
2. when pushing all.conf, sometimes the command fails with error 'unable to push config: % Invalid command' and we don't handle that condition gracefully (isse #126). I fixed the NoneType problem and added a retry logic to workaround the original issue, which seems to be Cisco specific.

Thanks

### CODE REVIEW

**Comment by jeremyschulman** [comment]
@acarpi - I started a review comment in the nxos-bootstrap script.  I've not done this before via github, so if you didn't see that, please review.  thank you.

**Comment by acarpi** [comment]
Re-target PR to merge into master.  @jeremyschulman  I haven't received your comment, sorry.

**Comment by jeremyschulman** [comment]
@acarpi - please read the comment in the above page regarding the "System ready" matter.

**Comment by bobbywatson3** [comment]
Thanks for this PR! I'm building a test environment for it now to review.

**Comment by jeremyschulman** [comment]
@acarpi - the reason why this exists is to ensure that the "System Ready" is there from the time of boot-up. Meaning I was trying to prevent a "false-positive" looking at the syslog file -- because that syslog file could have a previous "System ready" message from a previous run. By removing this mechanism, you may run the risk of hitting this issue. Do you agree; or is this not a concern in your mind?

**Comment by acarpi** [comment]
@jeremyschulman  we do rely on the same source of truth, so the concern should exist for your initial solution as well. 

In any case,  I verified both a first boot after ZTP and a reboot after a provisioned system: in both cases we have exactly one occurrence of 'System ready', so I think we are good there.

**Pull request merged**
